### PR TITLE
Show additional available hosts on server startup

### LINKED ISSUE #16: feature request: show network ip's on server started
As I often work on different networks I find myself having to look up my IP address so I can share it with coworkers and/or other devices. It would make my life a lot easier if wzrd could output all the IPv4 addresses on startup.

This would look something like this:
```bash
server started at:
http://127.0.0.1:9966
http://10.0.0.26:9966
http://192.168.0.2:9966
```
Node has native support for retrieving this information so it would not require additional dependencies. If you like this idea I'll start working on a PR so this feature can be added.

### PR DESCRIPTION
**Pull request by Arjen-Smit**
This outputs additional ipv4 based host names to the console on server start
```
server started at http://localhost:9966
also available at http://127.0.0.1:9966
also available at http://192.168.1.1:9966
```
This fixes #16 which I opened a few weeks ago.

### CODE REVIEW

**Comment by mafintosh** [comment]
looks good but we shouldn't show localhost then

**Comment by Arjen-Smit** [comment]
I wasn't 100% sure if every system has 127.0.0.1 available so I came up with this solution to make sure the unit tests wouldn't break. I will update my PR and add an additional checks to the unit-tests to make them work with the new output.
```
server started at:
http://127.0.0.1:9966
http://192.168.1.1:9966
```

**Comment by Arjen-Smit** [comment]
This should fix it.

**Comment by mafintosh** [comment]
1.4.0

**Pull request merged**
