### PR TITLE
Auto portfinding

### PR DESCRIPTION
**Pull request by mattdesl**
should no longer error when port is already in use

### CODE REVIEW

**Comment by mattdesl** [comment]
Added a basic test for portfinder; let me know if you have ideas about making it robust. 

Also changed `npm test` script since it was breaking for me.

**Comment by maxogden** [comment]
@mattdesl why are the 2 setTimeouts necessary in the first place?

**Comment by mattdesl** [comment]
Yeah, was hoping you'd have some ideas on how to avoid.

The process from the previous test is still on 9966 by the time the next test starts running.

**Comment by maxogden** [comment]
Ahh I see. It looks like the `tree-kill` module doesn't take a `done` callback (https://github.com/mattdesl/wzrd/blob/548741b0f62918a843640de6d233d4dbcbc41c1c/test/index.js#L24) so I guess we're stuck with this for now

**Comment by mafintosh** [comment]
couldn't you do `proc.on('exit', cb)`?

**Comment by mattdesl** [comment]
@mafintosh Yup that works on my OSX machine. Updated the test. :+1:

**Pull request merged**
